// pml::battle in-battle Pokémon struct — partial field map (Ultra Moon)
// AUTO-GENERATED by tools/usum_battlemon_fields.py from the indexed field
// getter sub_924a8 (Battle.cro). The btl engine is symbol-stripped, so
// offsets are recovered from the getter's relocated switch table + the
// per-case loads — the enum->offset mapping is exact/reproducible.
//
// CERTAIN: 0x1ea..0x1f0 are seven contiguous *signed* bytes read by seven
// consecutive getter cases — the stat-stage array. Scalar names elsewhere
// are best-effort (a live-battle dump would confirm them).
#pragma once
#include <cstdint>

namespace pml { namespace battle {

// Offsets are into the in-RAM battle-pokemon object (getter arg `this`).
struct BattlePokemonFields {
  /* 0x008 */ uint32_t  field_8;  // semantic TBD
  /* 0x00c */ uint16_t  field_c;  // semantic TBD
  /* 0x00e */ uint16_t  field_e;  // ? u16 HP pair with 0x10 — likely curHP (CatchRate reads HP here)
  /* 0x010 */ uint16_t  field_10;  // ? u16 HP pair with 0xe — likely maxHP
  /* 0x018 */ uint8_t   field_18;  // semantic TBD
  /* 0x01a */ uint8_t   field_1a;  // semantic TBD
  /* 0x01b */ uint8_t   field_1b;  // semantic TBD
  /* 0x0a0 */ uint32_t  field_a0;  // ? flag word (handler does tst #7)
  /* 0x1e7 */ uint8_t   field_1e7;  // semantic TBD
  /* 0x1ea */ int8_t    rankAtk;
  /* 0x1eb */ int8_t    rankDef;
  /* 0x1ec */ int8_t    rankSpAtk;
  /* 0x1ed */ int8_t    rankSpDef;
  /* 0x1ee */ int8_t    rankSpeed;
  /* 0x1ef */ int8_t    rankAccuracy;
  /* 0x1f0 */ int8_t    rankEvasion;
  /* 0x234 */ uint16_t  field_234;  // semantic TBD
};

// getter enum -> field (see battlemon_getter_fields.json):
//   2..8  -> rank{Atk,Def,SpAtk,SpDef,Speed,Accuracy,Evasion} (signed)
//   9..13 -> same first five via sub_81904 (apply-stage-to-stat path)
}} // namespace pml::battle
