// pml::pokepara::CoreParam — decrypted 232-byte Pokémon record layout
// AUTO-GENERATED by tools/usum_coreparam_fields.py from the named
// CoreParam::Get* accessors (Ultra Moon). Offsets are absolute in the
// decrypted blob; the four 56-byte data blocks A/B/C/D are stored
// PID-shuffled in RAM (see CoreParamLayout.cpp) — this view is the
// logical/unshuffled record. Every offset is read straight from the
// game's own accessor and anchor-checked against the canonical PK7 map.
#pragma once
#include <cstdint>

namespace pml { namespace pokepara {

// Block bases in the logical record: A=0x08 B=0x40 C=0x78 D=0xB0.
struct CoreParamFields {
  /* blk A abs 0x08 */ uint16_t  MonsNo;
  /* blk A abs 0x0a */ uint16_t  Item;
  /* blk A abs 0x0c */ uint32_t  ID;
  /* blk A abs 0x10 */ uint32_t  Exp;
  /* blk A abs 0x14 */ uint8_t   TokuseiNo;
  /* blk A abs 0x16 */ uint16_t  BoxMark;
  /* blk A abs 0x1c */ uint8_t   Seikaku;
  /* blk A abs 0x1d */ uint8_t   EventPokeFlag;  // mask 0x1
  /* blk A abs 0x1d */ uint8_t   Sex;
  /* blk A abs 0x1d */ uint8_t   FormNo;
  /* blk A abs 0x1e */ uint8_t   EffortPower;  // [indexed]
  /* blk A abs 0x2a */ uint8_t   ResortEventStatus;
  /* blk B abs 0x74 */ uint32_t  NativeTalentPower;  // [indexed] mask 0x1f
  /* blk C abs 0x93 */ uint8_t   Familiarity;
  /* blk C abs 0xae */ uint8_t   Feed;
  /* blk C abs 0xaf */ uint8_t   NadenadeValue;
  /* blk D abs 0xca */ uint8_t   OriginalFamiliarity;
  /* blk D abs 0xd1 */ uint8_t   Memories;
  /* blk D abs 0xdc */ uint8_t   GetBall;
  /* blk D abs 0xdd */ uint8_t   ParentSex;
  /* blk D abs 0xdf */ uint8_t   CassetteVersion;
  /* blk D abs 0xe3 */ uint8_t   LangId;
};

}} // namespace pml::pokepara
